### ISSUE TITLE
Read/Write directly into hadoop

### ISSUE THREAD

**Issue by vjsamuel** [himanshug/druid-hadoop-utils#2]
Hi,

We would like to know if it is possible to directly write data into hadoop without creating local file and then doing copyFromLocal and in similar fashion read directly from hadoop instead of copying to data node and then serving the data?

Thanks in advance.

Cheers,
 -Vijay

**Comment by himanshug** [comment]
that is not possible for now. however, what is the use case that does not work with existing way?

(also I'm going to overhaul this project in a few weeks with druid-0.8.1 release which has many new features to make things better here)

**Comment by vjsamuel** [comment]
We are looking to see if it is possible to load segments and query them directly from hadoop instead of copying into local machine and then loading them. It is basically a report of multiple metrics that we intend to store in segment files.

**Comment by himanshug** [comment]
sorry, I don't think that can be supported for now.
